require 'formula'
require 'json'

class IucPackagevcftools0112b < Formula
  version "1.0"
  # Recipe auto-generate from repository https://toolshed.g2.bx.psu.edu/iuc/package_vcftools_0_1_12b
  # Tool Shed Readme:
  #    
  #                A set of tools written in Perl and C++ for working with VCF files, such as those generated by the 1000 Genomes Project.
  #                http://vcftools.sourceforge.net/
  #            
  
  option "without-architecture", "Build without allowing architecture information (to force source install when binaries are available)."
  
  url "http://downloads.sourceforge.net/project/vcftools/vcftools_0.1.12b.tar.gz"
  sha1 ""
  
  def install
    system "make" 
    system "PREFIX=\"#{prefix}/vcftools\" make install" 
    system "cp bin/vcftools #{prefix}/vcftools/bin" 
    environment([{'action'=> 'prepend', 'variable'=> 'PATH', 'value'=> '$KEG_ROOT/vcftools/bin'},{'action'=> 'prepend', 'variable'=> 'PERL5LIB', 'value'=> '$KEG_ROOT/vcftools/lib/perl5/site_perl'}])
  end
  
  def environment(actions)
      # Setup envirnoment variable modifications that will be used later by
      # platform-brew's env and vinstall commands.
      act_hash = {"actions" => actions}
      (prefix / "platform_environment.json").write act_hash.to_json
  end
  
end