require 'formula'
require 'json'

class NileshVcftools < Formula
  version "1.0"
  # Recipe auto-generate from repository https://toolshed.g2.bx.psu.edu/nilesh/vcftools
  # Tool Shed Readme:
  #    
  #                A set of tools written in Perl and C++ for working with VCF files, such as those generated by the 1000 Genomes Project
  #            
  
  option "without-architecture", "Build without allowing architecture information (to force source install when binaries are available)."
  
  url "http://sourceforge.net/projects/vcftools/files/vcftools_0.1.11.tar.gz"
  sha1 ""
  
  def install
    system "make" 
    system "PREFIX=\"#{prefix}/vcftools\" make install" 
    environment([{'action'=> 'prepend', 'variable'=> 'PATH', 'value'=> '$KEG_ROOT/vcftools/bin'}])
  end
  
  def environment(actions)
      # Setup envirnoment variable modifications that will be used later by
      # platform-brew's env and vinstall commands.
      act_hash = {"actions" => actions}
      (prefix / "platform_environment.json").write act_hash.to_json
  end
  
end